spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/security
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dlwmal42

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug

    org.hibernate.type: trace



server:
  port: 8080




